/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.app

import advent.RunnableDay
import advent.days.Day01
import advent.days.Day02
import advent.days.Day03
import advent.days.Day04
import advent.days.Day16
import advent.days.Day19

fun main() {
  fun runDay(day: RunnableDay) {
    val result = day.run()
    println("Running $day")
    println("Part A: ${result.partA}")
    println("Part B: ${result.partB}")
  }

  runDay(Day19)
  runDay(Day16)
  runDay(Day04)
  runDay(Day03)
  runDay(Day02)
  runDay(Day01)
}
