/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main.kotlin.advent.app

import advent.RunnableDay
import main.kotlin.advent.days.Day01
import main.kotlin.advent.days.Day02

fun main() {
  fun runDay(day: RunnableDay) {
    val result = day.run()
    println("Running $day")
    println("Part A: ${result.partA}")
    println("Part B: ${result.partB}")
  }

  runDay(Day01)
  runDay(Day02)
}
