/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main.kotlin.advent.app

import main.kotlin.advent.days.Day01

fun main() {
  val result = Day01.run()
  println("Part A: ${result.partA}")
  println("Part B: ${result.partB}")
}
