/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main.kotlin.advent.app

class MessageUtils {
  companion object {
    fun getMessage(): String = "Hello      World!"
  }
}
