/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */ package advent.days

import advent.classes.day03.ClothClaim
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day03Test {
  @Test
  fun testPart1() {
    var input =
        listOf(
            ClothClaim.fromString("#1 @ 1,3: 4x4"),
            ClothClaim.fromString("#2 @ 3,1: 4x4"),
            ClothClaim.fromString("#3 @ 5,5: 2x2"))
    assertEquals("4", Day03.part1(input))
  }

  @Test
  fun testPart2() {
    var input =
        listOf(
            ClothClaim.fromString("#1 @ 1,3: 4x4"),
            ClothClaim.fromString("#2 @ 3,1: 4x4"),
            ClothClaim.fromString("#3 @ 5,5: 2x2"))
    assertEquals("3", Day03.part2(input))
  }
}
