/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */ package advent.days

import main.kotlin.advent.days.Day02
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day02Test {
  @Test
  fun testPart2() {
    var input = listOf("abcde", "fghij", "klmno", "pqrst", "fguij", "axcye", "wvxyz")
    assertEquals("fgij", Day02.part2(input))
  }
}
